### ISSUE TITLE
Ui Fixes in auth module

### ISSUE THREAD

**Issue by mohdnoorain** [mohdnoorain/parkcar#1]
> **Points to fix**

- Remove forgot password link fro signUp page
- Fix check box UI
- Add Sign up link in SignIn page
- Fix forgotPassword UI 
      - back button 
      - remove label 
- OtpVerification Ui fix 
      -  timer 
      - back button
      - resent button
- Reset password UI Fix
      - back button 
      - password show/hide

**Comment by Dheeru12503** [comment]
I am unable to change background color of checkbox.
